In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "Dados/MicrodadosTeresinaTratado2019.csv"

In [3]:
dadosEnem = pd.read_csv(path,sep=';',encoding='latin1',low_memory=False)

 <font color='red'>
    
## Ao agrupar valores/ trocar valores é importante considerar:
### Estamos trocando para Utilização com o Algoritmo Apriori

</font>

In [4]:
#Vou fazer um outro tratamento de dados, de acordo com as discussoes para remover colunas que não estamos usando.

dadosEnem = dadosEnem.drop(['NU_NOTA_COMP5'], axis=1)
dadosEnem = dadosEnem.drop(['NU_NOTA_COMP4'], axis=1)
dadosEnem = dadosEnem.drop(['NU_NOTA_COMP3'], axis=1)
dadosEnem = dadosEnem.drop(['NU_NOTA_COMP2'], axis=1)
dadosEnem = dadosEnem.drop(['NU_NOTA_COMP1'], axis=1)

dadosEnem = dadosEnem.drop(['CO_ESCOLA'], axis=1)
dadosEnem = dadosEnem.drop(['NO_MUNICIPIO_ESC'], axis=1)
#dadosEnem = dadosEnem.drop(['CO_MUNICIPIO_ESC'], axis=1)
dadosEnem = dadosEnem.drop(['TP_ENSINO'], axis=1)
dadosEnem = dadosEnem.drop(['TP_STATUS_REDACAO'], axis=1)
dadosEnem  = dadosEnem.drop(['NU_IDADE'], axis=1)

dadosEnem = dadosEnem.drop(['CO_MUNICIPIO_NASCIMENTO'], axis=1)
dadosEnem = dadosEnem.drop(['NO_MUNICIPIO_NASCIMENTO'], axis=1)
dadosEnem = dadosEnem.drop(['CO_UF_RESIDENCIA'], axis=1)
dadosEnem = dadosEnem.drop(['CO_MUNICIPIO_RESIDENCIA'], axis=1)
dadosEnem = dadosEnem.drop(['CO_UF_NASCIMENTO'], axis=1)
dadosEnem = dadosEnem.drop(['TP_ST_CONCLUSAO'], axis=1)
dadosEnem = dadosEnem.drop(['TP_ANO_CONCLUIU'], axis=1)
dadosEnem = dadosEnem.drop(['TP_ESCOLA'], axis=1)
dadosEnem = dadosEnem.drop(['SG_UF_ESC'], axis=1)
dadosEnem = dadosEnem.drop(['TP_SIT_FUNC_ESC'], axis=1)
dadosEnem = dadosEnem.drop(['NU_INSCRICAO'], axis=1)


dadosEnem = dadosEnem.drop(['IN_TREINEIRO'], axis=1)
dadosEnem = dadosEnem.drop(['NO_MUNICIPIO_PROVA'], axis=1)
dadosEnem = dadosEnem.drop(['CO_UF_PROVA'], axis=1)
dadosEnem = dadosEnem.drop(['TP_LINGUA'], axis=1)
#questionario
dadosEnem = dadosEnem.drop(['Q007'], axis=1)
dadosEnem = dadosEnem.drop(['Q008'], axis=1)
dadosEnem = dadosEnem.drop(['Q010'], axis=1)
dadosEnem = dadosEnem.drop(['Q011'], axis=1)
dadosEnem = dadosEnem.drop(['Q012'], axis=1)
dadosEnem = dadosEnem.drop(['Q013'], axis=1)
dadosEnem = dadosEnem.drop(['Q014'], axis=1)
dadosEnem = dadosEnem.drop(['Q015'], axis=1)
dadosEnem = dadosEnem.drop(['Q016'], axis=1)
dadosEnem = dadosEnem.drop(['Q017'], axis=1)
dadosEnem = dadosEnem.drop(['Q018'], axis=1)
dadosEnem = dadosEnem.drop(['Q019'], axis=1)
dadosEnem = dadosEnem.drop(['Q020'], axis=1)
dadosEnem = dadosEnem.drop(['Q021'], axis=1)
dadosEnem = dadosEnem.drop(['Q023'], axis=1)


# Agrupar faixas de Renda Q006
## De A ~ E -> Grupo 1
## De F ~ N -> Grupo 2
## De O ~   -> Grupo 3

In [5]:
dadosEnem["RendaMaxima"] = dadosEnem["Q006"]
dadosEnem["ClasseSocial"] = dadosEnem["Q006"]
var = "ClasseSocial"
dadosEnem[var].replace(to_replace =['A','B','C','D'], value ="0",inplace=True) 
dadosEnem[var].replace(to_replace =['E','F','G'],value ="1",inplace=True) 
dadosEnem[var].replace(to_replace =['H','I','J','K','L','M'], value ="C",inplace=True) 
dadosEnem[var].replace(to_replace =['N','O','P'], value ="B",inplace=True) 
dadosEnem[var].replace(to_replace =['Q'], value ="A",inplace=True) 
dadosEnem[var].replace(to_replace =['0'], value ="E",inplace=True) 
dadosEnem[var].replace(to_replace =['1'], value ="D",inplace=True) 
var = "RendaMaxima" 
dadosEnem[var].replace(to_replace =['A'], value =0,inplace=True) 
dadosEnem[var].replace(to_replace =['B'], value =998,inplace=True) 
dadosEnem[var].replace(to_replace =['C'], value =1497,inplace=True) 
dadosEnem[var].replace(to_replace =['D'], value =1996,inplace=True)
dadosEnem[var].replace(to_replace =['E'], value =2495,inplace=True) 
dadosEnem[var].replace(to_replace =['F'], value =2994,inplace=True) 
dadosEnem[var].replace(to_replace =['G'], value =3992,inplace=True) 
dadosEnem[var].replace(to_replace =['H'], value =4990,inplace=True) 
dadosEnem[var].replace(to_replace =['I'], value =5988,inplace=True) 
dadosEnem[var].replace(to_replace =['J'], value =6986,inplace=True) 
dadosEnem[var].replace(to_replace =['K'], value =7984,inplace=True) 
dadosEnem[var].replace(to_replace =['L'], value =8982,inplace=True) 
dadosEnem[var].replace(to_replace =['M'], value =9980,inplace=True) 
dadosEnem[var].replace(to_replace =['N'], value =11976,inplace=True) 
dadosEnem[var].replace(to_replace =['O'], value =14970,inplace=True) 
dadosEnem[var].replace(to_replace =['P','Q'], value =19960,inplace=True) 

dadosEnem = dadosEnem.drop(['Q006'], axis=1)



var = 'TP_DEPENDENCIA_ADM_ESC'
dadosEnem[var].replace(to_replace =[1.0], 
                 value ='Federal',inplace=True) #Federal
dadosEnem[var].replace(to_replace =[2.0], 
                 value ='Estadual',inplace=True) #Estadual
dadosEnem[var].replace(to_replace =[3.0], 
                 value ='Municipal',inplace=True) #Municipal
dadosEnem[var].replace(to_replace =[4.0], 
                 value ='Particular',inplace=True) #Particular


var = 'Q025'
dadosEnem[var].replace(to_replace =['A'], 
                 value ="Nao",inplace=True) 
dadosEnem[var].replace(to_replace =['B'], 
                 value ="Sim",inplace=True) 
var = 'Q022'
dadosEnem[var].replace(to_replace =['A'], 
                 value ='Não',inplace=True) 
dadosEnem[var].replace(to_replace =['B','C','D','E'], 
                 value ='Sim',inplace=True) 
var = 'Q024'
dadosEnem[var].replace(to_replace =['A'], 
                 value ='Não',inplace=True) 
dadosEnem[var].replace(to_replace =['B','C','D','E'], 
                 value ='Sim',inplace=True) 



var = 'Q009'
dadosEnem[var].replace(to_replace =['A'], 
                 value =0,inplace=True) 
dadosEnem[var].replace(to_replace =['B'], 
                 value =1,inplace=True) 
dadosEnem[var].replace(to_replace =['C'], 
                 value =2,inplace=True)
dadosEnem[var].replace(to_replace =['D'], 
                 value =3,inplace=True)
dadosEnem[var].replace(to_replace =['E'], 
                 value =4,inplace=True)

dadosEnem["anosEstudoPai"] = dadosEnem['Q001']
var = "anosEstudoPai"

dadosEnem[var].replace(to_replace =['A','H'], 
                 value =0,inplace=True) 
dadosEnem[var].replace(to_replace =['B'], 
                 value =4,inplace=True) 
dadosEnem[var].replace(to_replace =['C'], 
                 value =5,inplace=True)
dadosEnem[var].replace(to_replace =['D'], 
                 value =9,inplace=True)
dadosEnem[var].replace(to_replace =['E'], 
                 value =12,inplace=True)
dadosEnem[var].replace(to_replace =['F'], 
                 value =16,inplace=True) 
dadosEnem[var].replace(to_replace =['G'], 
                 value =18,inplace=True) 
var = 'Q001'
#dadosEnem[var].replace(to_replace =['A'], 
#                 value ='NaoEstudou',inplace=True) 
dadosEnem[var].replace(to_replace =['A','B','C'], 
                 value ='FundamentalIncompleto',inplace=True) 
dadosEnem[var].replace(to_replace =['D'], 
                 value ='FundamentalCompleto',inplace=True)
dadosEnem[var].replace(to_replace =['E'], 
                 value ='Medio',inplace=True)
dadosEnem[var].replace(to_replace =['F', 'G'], 
                 value ='Superior',inplace=True)
dadosEnem[var].replace(to_replace =['H'], 
                 value ='NaoSabe',inplace=True)

var = 'Q002'
#Ensino Fundamental
#dadosEnem[var].replace(to_replace =['B','C','D'], 
#                 value =1,inplace=True) 
#Ensino Médio
#dadosEnem[var].replace(to_replace =['E'], 
#                 value =2,inplace=True) 
#Ensino Superior, Pós Graduação
#dadosEnem[var].replace(to_replace =['F','G'], 
#                 value =3,inplace=True)
#Não sabe, Não estudou
#dadosEnem[var].replace(to_replace =['A','H'], 
#                 value =0,inplace=True)


dadosEnem["anosEstudoMae"] = dadosEnem['Q002']

var = "anosEstudoMae"

dadosEnem[var].replace(to_replace =['A','H'], 
                 value =0,inplace=True) 
dadosEnem[var].replace(to_replace =['B'], 
                 value =4,inplace=True) 
dadosEnem[var].replace(to_replace =['C'], 
                 value =5,inplace=True)
dadosEnem[var].replace(to_replace =['D'], 
                 value =9,inplace=True)
dadosEnem[var].replace(to_replace =['E'], 
                 value =12,inplace=True)
dadosEnem[var].replace(to_replace =['F'], 
                 value =16,inplace=True) 
dadosEnem[var].replace(to_replace =['G'], 
                 value =18,inplace=True) 

var = 'Q002'
#dadosEnem[var].replace(to_replace =['A'], 
#                 value ='NaoEstudou',inplace=True) 
dadosEnem[var].replace(to_replace =['A','B','C'], 
                 value ='FundamentalIncompleto',inplace=True) 
dadosEnem[var].replace(to_replace =['D'], 
                 value ='FundamentalCompleto',inplace=True)
dadosEnem[var].replace(to_replace =['E'], 
                 value ='Medio',inplace=True)
dadosEnem[var].replace(to_replace =['F', 'G'], 
                 value ='Superior',inplace=True)
dadosEnem[var].replace(to_replace =['H'], 
                 value ='NaoSabe',inplace=True)

#MediaAnosDeEstudo = dadosEnem[dadosEnem.Q002 != 'H'].Q002.mean()


var = 'Q003'
dadosEnem[var].replace(to_replace =['A','B','C'], 
                 value ="Grupo(A,B,C)",inplace=True) 
dadosEnem[var].replace(to_replace =['D','E'], 
                 value ="Grupo(D,E)",inplace=True) 
dadosEnem[var].replace(to_replace =['F'], 
                 value ="NãoSabe",inplace=True)


var = 'Q004'
dadosEnem[var].replace(to_replace =['A','B','C'], 
                 value ="Grupo(A,B,C)",inplace=True) 
dadosEnem[var].replace(to_replace =['D','E'], 
                 value ="Grupo(D,E)",inplace=True) 
dadosEnem[var].replace(to_replace =['F'], 
                 value ="NãoSabe",inplace=True)

#var = 'TP_SEXO'
#dadosEnem[var].replace(to_replace =['F'],value =1,inplace=True) 
#dadosEnem[var].replace(to_replace =['M'],value =0,inplace=True) 

var = 'TP_COR_RACA'
dadosEnem[var].replace(to_replace =[0],value ='NaoDeclarado',inplace=True) 
dadosEnem[var].replace(to_replace =[1],value ='Branco',inplace=True) 
dadosEnem[var].replace(to_replace =[2],value ='Preta',inplace=True) 
dadosEnem[var].replace(to_replace =[3],value ='Parda',inplace=True) 
dadosEnem[var].replace(to_replace =[4],value ='Amarelo',inplace=True) 
dadosEnem[var].replace(to_replace =[5],value ='Indigena',inplace=True) 


var = 'TP_LOCALIZACAO_ESC'
dadosEnem[var].replace(to_replace =[2],value ='Rural',inplace=True) 
dadosEnem[var].replace(to_replace =[1],value ='Urbano',inplace=True)

In [6]:
#Adicionando nova coluna quarto por pessoas e removendo as correspondentes 
pessoas = 'Q005' 
quartos = 'Q009'


dadosEnem[quartos].replace(to_replace =[0], 
                 value =1,inplace=True) 

dadosEnem['RazaoPessoasQuarto'] = (dadosEnem[pessoas]/dadosEnem[quartos])

precision = 2 

dadosEnem['RazaoPessoasQuarto'] = dadosEnem['RazaoPessoasQuarto'].round(decimals = precision)



dadosEnem = dadosEnem.drop([pessoas], axis=1) 
dadosEnem = dadosEnem.drop([quartos], axis=1)

#Adicionando nova coluna Média de anos de estudo e removendo

anos_pai = 'Q001'
anos_mae = 'Q002'

dadosEnem['SomaEstudoPais'] = (dadosEnem[anos_pai] + dadosEnem[anos_mae])
precision = 2
dadosEnem['SomaEstudoPais'] = dadosEnem['SomaEstudoPais'].round(decimals = precision)

#questionario
dadosEnem = dadosEnem.drop([anos_pai], axis=1)
dadosEnem = dadosEnem.drop([anos_mae], axis=1)

In [7]:
bins = [0,1,2,3,4,20]
dadosEnem['PessoasPorQuarto'] = pd.cut(dadosEnem['RazaoPessoasQuarto'],bins)
#df = pd.DataFrame(dadosEnem['PessoasPorQuarto'].value_counts(normalize=True).reset_index())
#df.columns  = ["Faixas","Porcentagem"]
#sns.barplot(x="Faixas", y="Porcentagem",data = df, hue="Faixas")

In [8]:
dadosEnem.query("NU_NOTA_CN == 0 or NU_NOTA_CH == 0 or NU_NOTA_LC == 0 or NU_NOTA_MT == 0")

,TP_SEXO,TP_COR_RACA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,CO_MUNICIPIO_ESC,...,Q004,Q022,Q024,Q025,RendaMaxima,ClasseSocial,anosEstudoPai,anosEstudoMae,RazaoPessoasQuarto,PessoasPorQuarto
213,M,Branco,Estadual,Urbano,363.0,0.0,500.1,516.1,0.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Nao,1497,E,0,12,1.67,"(1, 2]"
2624,F,Parda,Estadual,Urbano,442.2,0.0,453.9,374.1,480.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Nao,998,E,0,0,3.50,"(3, 4]"
3864,F,Parda,Estadual,Urbano,407.0,0.0,359.6,463.5,0.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Sim,998,E,4,4,1.50,"(1, 2]"
4538,F,Parda,Estadual,Urbano,329.1,444.2,412.7,0.0,0.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Nao,998,E,0,0,1.00,"(0, 1]"
4727,F,Amarelo,Estadual,Urbano,475.9,0.0,426.7,382.6,480.0,2211001.0,...,"Grupo(A,B,C)",Sim,Sim,Sim,998,E,0,0,1.50,"(1, 2]"
6420,F,Parda,Estadual,Urbano,419.9,0.0,351.2,511.7,440.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Nao,0,E,5,5,6.00,"(4, 20]"
6864,M,Parda,Estadual,Urbano,550.2,0.0,0.0,426.9,580.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Nao,1497,E,9,12,1.50,"(1, 2]"
6964,F,Branco,Federal,Urbano,466.0,0.0,492.0,0.0,0.0,2211001.0,...,"Grupo(A,B,C)",Sim,Não,Sim,998,E,5,9,1.50,"(1, 2]"

In [9]:
#Não pegando notas que por algum motivo tem valor zero
dadosEnem = dadosEnem.query("NU_NOTA_CN != 0 and NU_NOTA_CH != 0 and NU_NOTA_LC != 0 and NU_NOTA_MT != 0 and NU_NOTA_REDACAO != 0")

In [10]:
#column = 'Q005'
#for index, value in dadosEnem[column].items():
#        if(value <= 3):
#            dadosEnem[column][index] = 'TRE'
#        elif(value <= 7):
#             dadosEnem[column][index] = 'SET'
#        elif(value <= 10):
#             dadosEnem[column][index] = 'DEZ'
#        elif(value > 10):
#             dadosEnem[column][index] = 'MDEZ'

In [11]:
#Criando novas colunas pedidas pela Lorenza

#dadosEnem["MenorNota"] = dadosEnem.apply(lambda row: min(row.NU_NOTA_CH, row.NU_NOTA_LC,row.NU_NOTA_MT, row.NU_NOTA_REDACAO,row.NU_NOTA_CN), axis = 1)
#dadosEnem["MaiorNota"] = dadosEnem.apply(lambda row: max(row.NU_NOTA_CH, row.NU_NOTA_LC,row.NU_NOTA_MT, row.NU_NOTA_REDACAO,row.NU_NOTA_CN), axis = 1)

col = dadosEnem[['NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT','NU_NOTA_REDACAO','NU_NOTA_CN']]
dadosEnem['mediaNota'] = col.mean(axis=1)

In [12]:
#Discretizando notas
materias = ['NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT','NU_NOTA_REDACAO','NU_NOTA_CN']
bins = [0,300,500, 650, 800,1000]
dadosEnem['NOTA_MT'] = pd.cut(dadosEnem['NU_NOTA_MT'],bins)
dadosEnem['NOTA_LC'] = pd.cut(dadosEnem['NU_NOTA_LC'],bins)
dadosEnem['NOTA_CH'] = pd.cut(dadosEnem['NU_NOTA_CH'], bins)
dadosEnem['NOTA_CN'] = pd.cut(dadosEnem['NU_NOTA_CN'], bins)
dadosEnem['NOTA_REDACAO'] = pd.cut(dadosEnem['NU_NOTA_REDACAO'], bins,include_lowest=True)

In [13]:
#Adicionando coluna macroregião

#dadosCidades = pd.read_csv('Cidades_MG_IESP_2.csv',sep=';',encoding='latin1',usecols=['Nome_Mesorregiao','Nome_Microrregiao','CO_MUNICIPIO_ESC','IndiceGini','NO_MUNICIPIO'])
#dadosEnem['CO_MUNICIPIO_ESC'] = dadosEnem['CO_MUNICIPIO_ESC'].astype('int')
#dadosEnem['CO_MUNICIPIO_ESC']

In [14]:
#dadosEnem.columns = ['RACA','SEXO','DependenciaEsc','LocalizacaoEsc','''EstudoMae','EstudoPai','TrabalhoMae']
#dadosEnem.to_csv("MicrodadosParaRegrasAssociacao.csv", encoding='latin1', index=False,sep=';')
notas = dadosEnem[['RendaMaxima','NU_NOTA_MT','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_CN','NU_NOTA_REDACAO']]
notas.to_csv('notasParaClusterizacao2019.csv',encoding='latin1', index=False,sep=';')

In [15]:
#dadosEnem = dadosEnem.drop(['NU_NOTA_MT','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_CN','NU_NOTA_REDACAO','mediaNota','RazaoPessoasQuarto'], axis=1)
dadosEnem.to_csv('dadosParaMineracaoRegrasAssociacao2019.csv',encoding='latin1', index=False,sep=';')

KeyError: 'Q006'

In [17]:
dadosEnem['ClasseSocial'].value_counts()

E    4645
D     978
C     742
B     275
A     108
Name: ClasseSocial, dtype: int64


from sklearn.preprocessing import LabelBinarizer


raca = pd.get_dummies(dadosEnem.TP_COR_RACA, prefix='RACA')
sexo = pd.get_dummies(dadosEnem.TP_SEXO, prefix='SEXO')
dependencia_esc = pd.get_dummies(dadosEnem.TP_DEPENDENCIA_ADM_ESC, prefix='DependenciaEsc')
localizacao_esc = pd.get_dummies(dadosEnem.TP_LOCALIZACAO_ESC, prefix='LocalizacaoEsc')
q001 = pd.get_dummies(dadosEnem.Q001, prefix='EstudoPai')
q002 = pd.get_dummies(dadosEnem.Q002, prefix='EstudoMae')
q003 = pd.get_dummies(dadosEnem.Q003, prefix='TrabalhoPai')
q004 = pd.get_dummies(dadosEnem.Q004, prefix='TrabalhoMae')
q005 = pd.get_dummies(dadosEnem.Q005, prefix='NumPessoas')
q006 = pd.get_dummies(dadosEnem.Q006, prefix='GrupoRenda')
q009 = pd.get_dummies(dadosEnem.Q006, prefix='NumQuartos')
q022 = pd.get_dummies(dadosEnem.Q022, prefix='Celular')
q024 = pd.get_dummies(dadosEnem.Q024, prefix='Computador')
q025 = pd.get_dummies(dadosEnem.Q025, prefix='Internet')
mesoregiao =pd.get_dummies(dadosEnem.Nome_Mesorregiao, prefix='Mesoregiao')
notas_mt = pd.get_dummies(dadosEnem.NU_NOTA_MT, prefix='NU_NOTA_MT')
notas_cn = pd.get_dummies(dadosEnem.NU_NOTA_CN, prefix='NU_NOTA_CN')
notas_ch = pd.get_dummies(dadosEnem.NU_NOTA_CH, prefix='NU_NOTA_CH')
notas_lc = pd.get_dummies(dadosEnem.NU_NOTA_LC, prefix='NU_NOTA_LC') 
notas_red = pd.get_dummies(dadosEnem.NU_NOTA_REDACAO, prefix='NU_NOTA_REDACAO')

#para rodas os algoritmos vai ser necessario passar pelas colunas para criar a tabela de itens

encoded_values = pd.pandas.concat([raca, sexo,dependencia_esc,localizacao_esc,mesoregiao,notas_mt,notas_cn,notas_ch,notas_lc,notas_red,q001,q002,q003,q004,q005,q006,q009,q022,q024,q025], axis=1)


encoded_values.replace(0, np.nan,inplace=True)
encoded_values = encoded_values.astype('category')
encoded_values.to_csv("BinaryEncoded_ALL.csv", encoding='latin1', index=False,sep=';')

encoded_values.info()
encoded_values.to_csv("Encoded_ALL.csv", encoding='latin1', index=False,sep=';')
# Iterate over the sequence of column names
#for column in encoded_values:
# Select column contents by column name using [] operator
#    columnSeriesObj = encoded_values[column]
#       if(value == 1):
#            encoded_values[column][index] = column